title: CarlosMendonca
description: Computer Engineer from 🇧🇷. Product Manager @ Google AI in 🗽. Ex-Microsoft. I take pictures of the stars.
baseurl: ""
url: "https://carlosmendonca.github.io"
twitter_username: chemendonca
github_username:  CarlosMendonca

search_enabled: false

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:

footer_content: "<a href=\"https://twitter.com/chemendonca\" target=\"_blank\">Twitter</a> | <a href=\"https://www.linkedin.com/in/carlosmendonca\" target=\"_blank\">LinkedIn</a> | <a href=\"https://github.com/CarlosMendonca\" target=\"_blank\">GitHub</a>"

color_scheme: grayscale

# Google Analytics Tracking (optional)
ga_tracking: UA-142835847-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

# Build settings
markdown: kramdown
permalink: pretty

remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
